Corrección de error OxxoPay
conekta/conektaprestashop pull request #56
Opened 2017-06-16 22:46 UTC by JoValo

Se estaba haciendo un SELECT de _conekta_transactions_ sobre los registros que tuvieran el STATUS _paid_ lo cual regresaba **NULL** en el caso de las transacciones hechas por OxxoPay. 

Debajo se esta haciendo la siguiente validación:

```
if ($conekta_transaction_details['status'] === 'paid') { 
     //set color and message status
} 
else {
     //set color and message status
}
```

2017-06-19 18:26 UTC, fruizg0302 requested changes

2017-06-19 18:26 UTC, fruizg0302 commented on conektaprestashop.php
> +            $conekta_transaction_details = Db::getInstance()->getRow('SELECT * FROM ' . _DB_PREFIX_ . 'conekta_transaction WHERE id_order = ' . pSQL((int) $id_order) . ' AND type = \'payment\'');
Estaría chido para mejorar la legibilidad del query separarlo en varias lineas (siempre y cuando el query no vaya a hacer cosas raras por este cambio)

2017-06-19 18:26 UTC, fruizg0302 commented on conektaprestashop.php
> -            $conekta_transaction_details = Db::getInstance()->getRow('SELECT * FROM ' . _DB_PREFIX_ . 'conekta_transaction WHERE id_order = ' . pSQL((int) $id_order) . ' AND type = \'payment\' AND st
Gracias Llorch, cómo te comentaba en vivo y en directo, ya que hacen lo mismo me gustaría que se pudiera extraer esta lógica a un método. Siempre y cuando esto no genere comportamiento inesperado por parte del plugin.

2017-06-19 22:57 UTC, fruizg0302 approved these changes
👍 Muchas gracias

2017-06-20 19:08 UTC, luiscarlos-gonzalez requested changes

2017-06-20 19:08 UTC, Kentverger commented on conektaprestashop.php
> +        if (Db::getInstance()->getValue(
Que opinas de cambiar esta query a un query method para que al final quede algo como:

```
public function module($order_id) {
   return Db::getInstance()->getValue(
            'SELECT module FROM ' . _DB_PREFIX_ . 'orders '
            .'WHERE id_order = ' . pSQL((int) $id_order))
}
```

y el if:

`if(module(order_id) == $this->name)`

igual para la linea 935

2017-06-20 19:41 UTC, JoValo commented on conektaprestashop.php
> +        if (Db::getInstance()->getValue(
Gracias por la observación @Kentverger

2017-06-20 20:24 UTC, fruizg0302 approved these changes
👍

2017-06-20 20:32 UTC, luiscarlos-gonzalez requested changes
Ya solo deja un solo commit usando `git rebase -i HEAD~5`

2017-06-20 20:45 UTC, luiscarlos-gonzalez approved these changes

2017-06-20 20:57 UTC, merged