Feature/headers prestashop
conekta/conektaprestashop pull request #68
Opened 2017-08-08 18:27 UTC by JoValo

2017-08-08 18:34 UTC, vicentemendoza requested changes

2017-08-08 18:34 UTC, vicentemendoza commented on conektaprestashop.php
> +                        'amount' => (float)$discount['value_real'] * 100,
aqui son centavos? no deberia de ser int?

2017-08-08 18:57 UTC, JoValo commented on conektaprestashop.php
> +                        'amount' => (float)$discount['value_real'] * 100,
Gracias Vicent de hecho iba así:
`'amount' => (int)((float)$discount['value_real'] * 100),`
pero no salve el cambio por que solo con int no coincide el valor que se manda con el de la orden:
![captura de pantalla 2017-08-08 a la s 13 39 52](https://user-images.githubusercontent.com/17298066/29089287-64c841f4-7c41-11e7-8db5-fb59389f5f4f.png)
![captura de pantalla 2017-08-08 a la s 13 40 08](https://user-images.githubusercontent.com/17298066/29089286-64c7771a-7c41-11e7-8fcd-74948f2bf1b5.png)

2017-08-08 20:06 UTC, julsdelatierra requested changes

2017-08-08 20:06 UTC, jcebXD commented on conektaprestashop.php
>          \Conekta\Conekta::setApiKey(Configuration::get('CONEKTA_MODE') ? Configuration::get('CONEKTA_PRIVATE_KEY_LIVE') : Configuration::get('CONEKTA_PRIVATE_KEY_TEST'));
Esto supera los 80 caracteres, quizas guardar en variables las llaves.

2017-08-08 20:06 UTC, jcebXD commented on conektaprestashop.php
> +                    'unit_price'  => (int) round((float)$item['price'] * 100),
Este cast tiene un espacio en blanco y mas adelante no la tiene, cual es la recomendación de la guía?

2017-08-08 20:06 UTC, jcebXD commented on conektaprestashop.php
> +                        'amount' => (float)$discount['value_real'] * 100,
Este cast no tiene espacio, anteriormente se ponía un espacio.

2017-08-10 16:30 UTC, jakumx approved these changes

2017-08-11 22:08 UTC, vicentemendoza approved these changes

2017-08-15 20:49 UTC, RamsesCarbajal approved these changes

2017-08-16 16:49 UTC, fruizg0302 approved these changes

2017-08-16 17:36 UTC, merged